### ISSUE TITLE
can't scroll

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/jupyterlab-plugin#1]
<img width="1407" alt="screen shot 2018-05-25 at 06 39 55" src="https://user-images.githubusercontent.com/264658/40527945-d28f0cb6-5fe6-11e8-9a29-730d8000cc58.png">

the commit list isn't scrollable

**Comment by lukemarsden** [comment]
@binocarlos how's progress on this?

**Comment by prisamuel** [comment]
Done!
