### ISSUE TITLE
[0.5d] plugin should inform user if committer dies

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/jupyterlab-plugin#13]
The committer died from not being able to parse some JSON. The status bar however doesn't change despite receiving an error in the backend (visible in the console).

### ACs

- [x] If the committer does not respond to status requests, the status shown to the user should be a suitable error message.

### Future notes

Some way of recovering from this situation should be sought and implemented, but it may not be possible to do anything better than to tell the user to save, exit, and restart Jupyter?

**Comment by Godley** [comment]
![screenshot 2019-01-07 at 17 51 47](https://user-images.githubusercontent.com/4128117/50784251-0720ba80-12a5-11e9-8c7a-34dfac8268bf.png)

Not sure how we define suitable error here but this is what I've put in. In theory there could be more specifics to the error which we could surface.

@alice-sowerby going to put you up for review on this again :)

**Comment by alice-sowerby** [comment]
Looks good, can you tune the wording to be more user friendly. Does this cover it? 

`An error has occurred and changes are not being saved in Dotscience. Please restart JupyterLab to fix this issue.`

**Comment by Godley** [comment]
👍 will do, thank you!
