### ISSUE TITLE
[0.5d] Update plugin to correctly display errors from the committer

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/jupyterlab-plugin#14]
We changed the way errors are reported from the committer to the plugin. We don't know if the plugin already has code to display errors that now needs changing, or if that still needs writing...

1) status "error" is now gone. We figured the next pass we're just going to change the status back to waiting, so it's a pointless status. Instead, check the length of errorDetail and show those errors
2) errorDetail is now a list of errors, not an object. This is so that we don't overwrite the old error. 

## ACs

- [x] Errors reported by the committer should be visible in the Jupyter plugin.
- [x] Where possible, errors should be linked somehow to the location the error comes from in the workbook.
- [ ] implement feedback from comments

**Comment by Godley** [comment]
![screenshot 2019-01-07 at 17 27 08](https://user-images.githubusercontent.com/4128117/50783416-b60fc700-12a2-11e9-938c-2b7d832121b9.png)
![screenshot 2019-01-07 at 17 34 56](https://user-images.githubusercontent.com/4128117/50783417-b60fc700-12a2-11e9-8aab-90478c668ca0.png)


@alice-sowerby this is now ready for sign off, but I'm not super happy about the design side of things - to me when you have multiple errors it's a bit cluttered/harder to read. If I could get some input from @petercolesdc @danthebaker on how to make it better that'd be great

**Comment by Godley** [comment]
(assigned those people to review this)

**Comment by alice-sowerby** [comment]
Thanks Charlotte, we need some user friendly wording showing: 

* the problem
* what they should do

e.g. There is a JSON error, please save and restart Jupyter. 

WDYT?

**Comment by alice-sowerby** [comment]
> We couldn't process the dotscience output in notebook x cell y, please check it is valid JSON (linktojsonparser?)

If it's a Dotscience fault maybe it should read
> Dotscience has output invalid JSON, this is an error, please [contact support]
 
>We couldn't parse the notebook x, please check it is valid JSON or remove it.

If the notebook format is incorrect or corrupted, how about 
> We couldn't read the notebook x, please check it is saved in the correct JSON format.
