### ISSUE TITLE
[INTERRUPTION] getting commits is now broken

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/jupyterlab-plugin#15]
Agent now clones dots as `username/dotname` or similar. This means that the plugin's assumptions are wrong (trim off the namespace and just use the username "admin") and results in 500 errors on the runner when getting commits.

Think the fix is to just use `dotNameFromOptionalNamespace` thingy without the `.name` part on the end

**Comment by binocarlos** [comment]
the fix for the commits showing up in the plugin is now pushed as `quay.io/dotmesh/jupyterlab-tensorflow:test-latest` [pipeline](https://gitlab.dotmesh.com/dotmesh/e2e-sync/-/jobs/143447)

**Comment by danthebaker** [comment]
Commits now showing.
