### ISSUE TITLE
[INTERRUPTION] Plugyn logging is too verbose!

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/jupyterlab-plugin#16]
The plugyn repeatedly logs this kind of thing:

```
Loading logs for dot: ds-2I4UDIC7MHWXXHJH7MF3EGZPUGQALCJBUY6T5RLKTUW3BEBIORTQ from url: http://172.18.0.1:32607/rpc
Loading committer status from url: http://ds-9af334d0-f092-4384-a6be-ca968c05ad4f/status
{\"unclaimed_files\": [], \"status\": \"waiting\", \"notebooks\": {}, \"changed_files\": []}
```

Those logs get stored on the gateway and carried all the way to the frontend, just to be ignore most of the time, so should probably be disabled unless debug logging is explicitly requested (NB: If you look for an env var called `TASK.DEBUG_LOGGING`, it can be set from the frontend by putting a label called `DEBUG_LOGGING` in the task record)

**Comment by binocarlos** [comment]
The plugin now only logs if the `TASK.DEBUG_LOGGING` env variable is a non-empty string

**Comment by binocarlos** [comment]
I have bumped the https://github.com/dotmesh-io/jupyterlab-tensorflow Docker image with this fix
