### ISSUE TITLE
[INTERRUPTION] Summarise large file lists in the plugin

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/jupyterlab-plugin#19]
When we have hundreds of files changed but not committed, or committed in a run, the JupyterLab plugin crashes the browser due to dealing with massive files.

All the metadata about all the files end up being sent to the browser, so browser gets very slow - show a limited number (e.g. 10) changed files and info e.g. "and 103 more" in JupyterLab plugin.

- Filter the commit metadata in the Python backend of the plugin.
- Trim down agent “committer status” in the agent.
- (optional) Change polling into either websocket events or SSE

**Comment by rusenask** [comment]
merged
