### ISSUE TITLE
jupyterLab loses local changes to a file after 'ds run' upon browser reload

### ISSUE THREAD

**Issue by eugenemi** [dotmesh-io/jupyterlab-plugin#23]
I opened up a project in jupiterLab, opened up test.py, changed a comment in it and saved it using File/Save Python File menu optin.
Then on my laptop, executed `ds run . deb4695c-fadb-4342-b8b5-0a69772892f4 python:3 python test.py` in the same project with the unmodified version of test.py.
I then reloaded jupyterLab in the browser.  test.py reverted to the unmodified version, and Dotscience Tab showed no files displaying just "Status: waiting".

**Comment by alaric-dotmesh** [comment]
This is a locking problem!

**Comment by alice-sowerby** [comment]
Closing as now covered by https://github.com/dotmesh-io/gateway/issues/180
