### ISSUE TITLE
[0.5d] Clear 'cannot read notebook errors'

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/jupyterlab-plugin#27]
when there is a 'cannot read notebook' error in the dotscience jupyter tab (from the committer) - make sure it's cleared if it works again.

Presently the error remains even though the issue has resolved itself

**Comment by lukemarsden** [comment]
i am possibly fixing this by making the plugin not stop polling on error (previously on any error it would not poll again)

**Comment by lukemarsden** [comment]
verified fixed! by unplugging network on my laptop and plugging it back in again
