### ISSUE TITLE
Regression: jupyterlab-plugin now blatting errors about invalid dot names

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/jupyterlab-plugin#6]
Since Alaric changed the dot name passed in to the jupyter instance via environment variable to include the namespace in `ns/name` form, the jupyterlab-plugin is failing with an error from dotmesh because the getDot python-sdk API takes `dotname, ns=foo` type arguments but we are passing `ns/name` as `dotname`.

Currently, https://github.com/dotmesh-io/jupyterlab-tensorflow isn't building, hence the existence of the `argh` directory which embeds a copy of `__init__.py` from the plugin at  
https://github.com/dotmesh-io/jupyterlab-plugin. However to fix this properly, we should start using the [new parser](https://github.com/dotmesh-io/python-sdk/commit/9016db0359e6a3497529abd9ce7905973a82ed09) in the python SDK.

However, to upgrade the version of the python sdk, we either have to:
1. Extend the hack in `jupyterlab-tensorflow/argh` to also update the version of the python-sdk (datadots-api) library, or
2. Figure out why https://github.com/dotmesh-io/jupyterlab-tensorflow isn't building and fix that, so that we can start building the image properly again.

My preference is for the latter - we need to do this soon anyway. Let's sort it out and then, for bonus points, add jupyterlab-tensorflow image to CI so that it automatically builds new images.

**Comment by lukemarsden** [comment]
Just tested this and jupyterlab-tensorflow is building again! Yay!

**Comment by alaric-dotmesh** [comment]
Fixed!
