### ISSUE TITLE
[2d] Make Jupyter plugin show live committer status and guide users towards dotsciencifying their notebooks

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/jupyterlab-plugin#7]
Show committer status in the Jupyter plugin, eg
- no files changed
- 100kb of changes (phase 2 - these files have changed, with hints on how to recognise them as outputs in the annotations - please split this into a new issue if not done in this issue)
- committing
- synchronising/pushing (live status updates)
- invalid JSON found

And so forth. Either give the committer an API, or make it write to the output slot (per @alaric-dotmesh suggestion).

See related issue for backend - see https://github.com/dotmesh-io/dotscience-committer/issues/16

**Comment by binocarlos** [comment]
I've just created #8 to capture the "display the annotations needed" part of this issue

**Comment by binocarlos** [comment]
This is working against fixture data from a server that is running in local-stack - you can read how to run this in the [local-stack Readme here](https://github.com/dotmesh-io/local-stack/tree/local-stack-ng#run-the-committer-and-jupyterlab-plugin-locally)

Once we have [the committer issue](https://github.com/dotmesh-io/dotscience-committer/issues/16) closed - we can wire up the committer into local-stack and the data can be for reals.
