### ISSUE TITLE
[1d] Show the changed files in the dotscience jupyter plugin and show how to annotate them

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/jupyterlab-plugin#8]
As part of #7 we are displaying a list of the changed files as far as the committer is aware.

This issue is about guiding the user towards annotating those files as input or output as per the [run metadata spec](https://github.com/dotmesh-io/dotscience-docs/blob/master/hugo/content/references/run-metadata-format.md)

**Comment by alaric-dotmesh** [comment]
This depends on https://github.com/dotmesh-io/dotscience-committer/issues/16

**Comment by binocarlos** [comment]
I guess actually the only things we can show are:
• number of runs detected in a given notebook (to indicate that maybe user hasn't published any runs yet, they need to start using the python library)
• modified files that aren't recorded in any runs
because all the other things (e.g. which inputs are declared etc) are all captured in a run which is immediately pushed
so for me these are the three UI elements we need
1. committer status (waiting, committing, pushing - later let's add more detail to pushing like MB/sec and an ETA like in `dm push`)
2. list of notebooks with runs in, how many runs in each notebook (a zero here indicates that you need to use the python library to publish runs at all)
3. any modified files that aren't recorded in any runs (this is a hint that users should flag output files with the python library)

**Comment by Godley** [comment]
Spent some time investigating this but I don't have a clear view on what the UI should look like for what is remaining, and the build process fails for me/results in jupyterlab with no plugin visible. Blocked waiting for @binocarlos 's return :)
