### ISSUE TITLE
[0.5d remaining EXTRA] Wire this up to CI

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/jupyterlab-plugin#9]
So we have a few options here:

1. We have this repo trigger the jupyterlab-tensorflow repo and send it the sha1 hash. In the docker image of that repo we have it check out that sha1 hash in the `git clone` line. This seems the fastest (should take less than an hour) and least fiddly approach but if we're thinking of open sourcing this might look a bit hacky to outsiders/python devs
1. We release the plugin on pypi using semantic versioning via `git tag` then do something similar to the above but use pip to install it. This is more pythonic and means we release new versions which have meaning rather than just a sha1 commit, but takes some more wiring.

**Comment by Godley** [comment]
We could also just merge this repo with the other repo containing the docker image. I don't really understand why they're separate - @binocarlos or @lukemarsden probably have their reasons?

**Comment by alaric-dotmesh** [comment]
Everyone likes option 2.

1. Tag a plugin release as a version
2. CI builds and deploys it to pypi
3. CI also triggers a rebuild of jupyterlab-tenserflow that does a `pip install` of the new version.

**Comment by Godley** [comment]
Think this is now done, release process is the same as the others (`git tag <semver> && git push --tags`), it then releases to pypi and npm, then triggers jupyterlab-tensorflow which then installs those tags and has a docker tag of `<commit-sha>-ds-<tag-or-latest>-plugyn-<tag-or-latest>`. Have checked visually using local-stack and it all looks happy and running properly :)
